[patch.crates-io]
blst = { git = "https://github.com/supranational/blst", rev = "fb91221c" }
sppark = { git = "https://github.com/supranational/sppark" }
bellperson = { path = "c2/bellperson", version = "0.24.1"}
